---
settings:
  name: Application and Database Best Practice and Implementation Guides
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
sidebar:
  entries:
    - title: Application and Databases
      url: /index.html
    - section: mysql
    - section: mssql
    - section: oracle
    - section: postgres
    - section: hana
    - title: Legal notices
      url: /legal-notices.html
