---
settings:
  name: Implementation Guides
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
sidebar:
  entries:
    - title: Implementation Guides
      url: /index.html
    - section: common
    - section: mysql
    - section: mssql
    - section: oracle
    - section: postgres
    - section: hana
    - section: virtualization 
    - title: Legal notices
      url: /legal-notices.html
