---
settings:
  name: Enterprise Applications
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
sidebar:
  entries:
    - title: Enterprise Applications
      url: /index.html
    - section: common
    - section: mssql
    - section: mysql
    - section: oracle
    - section: postgres
    - section: hana
    - title: Virtualization
      entries:
      - section: vmware
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: ONTAP
  repo: ontap-family