---
settings:
  name: Enterprise applications
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
sidebar:
  entries:
    - title: Enterprise applications
      url: /index.html
    - section: common
    - section: mssql
    - section: mysql
    - section: oracle
    - section: postgres
    - section: hana
    - section: vmware
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: ONTAP technical reports
  repo: ontap-technical-reports 