settings:
  name: Enterprise applications
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: Enterprise applications
      url: /index.html
    - section: mssql
    - section: mysql
    - section: oracle
    - section: postgres
    - title: SAP HANA and AnyDB
      entries:
         title: 
         url: sap-solutions.html
    - section: vmware
    - title: Legal notices
      url: /legal-notices.html