settings:
  name: Enterprise applications
  search: ontap-technical-reports, ontap-apps-dbs, netapp-solutions-sap
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: Enterprise applications
      url: /index.html
    - section: epic
    - section: Hyper-V      
    - section: mssql
    - section: mysql
    - section: oracle
    - section: postgres
    - title: SAP
      entries:
         - title: SAP HANA and AnyDB
           url: sap-solutions.html
    - section: vmware
    - title: Legal notices
      url: /legal-notices.html
      