settings:
  name: Enterprise applications
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: false
sidebar:
  entries:
    - title: Enterprise applications
      url: /index.html
    - section: mssql
    - section: mysql
    - section: oracle
    - section: postgres
    - title: SAP HANA
      url: https://docs.netapp.com/us-en/netapp-solutions-sap/
    - section: vmware
    - title: Legal notices
      url: /legal-notices.html