---
sidebar: sidebar
permalink: oracle/oracle-asar2-storage-san-config-asru.html
keywords: ontap, thin provisioning, oracle, ASRU, ASA r2
summary: ASM Reclamation Utility with ONTAP zero-block detection on ASA r2
searchtitle: ASM Reclamation Utility (ASRU) with ONTAP on ASA r2
---
= ASM Reclamation Utility (ASRU)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
ONTAP on ASA r2 efficiently removes zeroed blocks written to a LUN (storage unit) when inline compression is enabled. Utilities such as the Oracle ASM Reclamation Utility (ASRU) work by writing zeros to unused ASM extents.

This allows DBAs to reclaim space on the storage array after data is deleted. ONTAP intercepts the zeros and deallocates the space from the LUN. The reclamation process is extremely fast because no actual data is being written within the storage system.

From a database perspective, the ASM diskgroup contains zeros, and reading those regions of the LUNs would result in a stream of zeros, but ONTAP does not store the zeros on drives. Instead, simple metadata changes are made that internally mark the zeroed regions of the LUN as empty of any data.

For similar reasons, performance testing involving zeroed data is not valid since blocks of zeros are not actually processed as writes within the storage array.

Key ASRU considerations with ASA r2 ONTAP:

* Works the same way as AFF/FAS for SAN workloads because ASA r2 is block-only.
* Applies to LUNs and NVMe namespaces provisioned within SAZs. 
* No FlexVol volumes exist, but the zero-block reclamation behavior is identical.

[NOTE]
When using ASRU, ensure that all Oracle-recommended patches are installed.