---
sidebar: sidebar
permalink: oracle/oracle-dr-overview.html
keywords: metrocluster, syncmirror, oracle
summary: Oracle database disaster recovery with ONTAP
searchtitle: Oracle database disaster recovery with ONTAP
---
= Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Disaster recovery refers to restoring data services after a catastrophic event, such as a fire that destroys a storage system or even an entire site.

[NOTE]
This documentation replaces previously published technical reports _TR-4591: Oracle Data Protection_ and _TR-4592: Oracle on MetroCluster._ 

Disaster recovery can be accomplished by simple replication of data using SnapMirror, of course, with many customers updating mirrored replicas as often as hourly. 

For most customers, DR requires more than just possessing a remote copy of data, it requires the ability to rapidly make use of that data. NetApp offers two technologies that address this need - MetroCluster and SnapMirror active sync

MetroCluster refers to ONTAP in a hardware configuration that includes low-level synchronously mirrored storage and numerous additional features. Integrated solutions such as MetroCluster simplify today's complicated, scale-out database, application, and virtualization infrastructures. It replaces multiple, external data protection products and strategies with one simple, central storage array. It also provides integrated backup, recovery, disaster recovery, and high availability (HA) within a single clustered storage system.

SnapMirror active sync (SM-as) is based on SnapMirror Synchronous. With MetroCluster, each ONTAP controller is responsible for replicating its drive data to a remote location. With SnapMirror active sync, you essentially have two different ONTAP systems maintaining independent copies of your LUN data, but cooperating to present a single instance of that LUN. From a host point of view, it's a single LUN entity.

== SM-as and MCC comparison

include::../_include/dr-mcc-smas-compared.adoc[]