---
sidebar: sidebar
permalink: mssql/mssql-overview.html
keywords: MS-SQL,mssql,SQL Server,TR-4590
summary: Microsoft SQL Server on ONTAP
---
= Microsoft SQL Server on ONTAP
:imagesdir: ../media/

[.lead]
NetApp ONTAP and Microsoft SQL Server helps to deliver enterprise-class secured and performant solution while providing world-class tools to manage your environment. ONTAP's several features and capabilities help in optimizing operations and realize the power of your data on the premises or in the cloud.

[NOTE]
This documentation replaces the previously published technical report _TR-4590: Best practice guide for Microsoft SQL Server with ONTAP_

To achieve effective and efficient storage deployment, end-to-end data protection, retention planning on NetApp storage and insight into design considerations for deploying SQL Server databases there are few clear best practices for configuring SQL Server on ONTAP. This enable SQL Server architects and NetApp storage administrators to plan a highly available and easy-to-manage SQL Server environment and to meet stringent SLAs. NetApp assumes that the reader has working knowledge of the following: 

* NetApp ONTAP software
* NetApp SnapCenter as backup software, which includes:
    - SnapCenter Plug-in for Microsoft Windows
    - SnapCenter Plug-in for SQL Server
* Microsoft SQL Server architecture and administration 

The scope of this best practices is limited to technical design based on the design principles and preferred standards that NetApp recommends for storage infrastructure. The end-to-end implementation is out of the scope. 

For configuration compatibility across the NetApp products, see the link:https://mysupport.netapp.com/matrix/[NetApp Interoperability Matrix Tool (IMT)^].

== Microsoft SQL Server workloads

Before deploying SQL Server, you must understand the database workload requirements of the applications that your SQL Server instances support. Each application has different requirements for capacity, performance, and availability, and therefore each database should be designed to optimally support those requirements. Many organizations classify databases into multiple management tiers, using application requirements to define SLAs. SQL Server workloads can be described as follows:

* OLTP databases are often also the most critical databases in an organization. These databases usually back customer-facing applications and are considered essential to the company's core operations. Mission-critical OLTP databases and the applications they support often have SLAs that require high levels of performance and are sensitive to performance degradation and availability. They might also be candidates for Always On Failover Clusters or Always On Availability Groups. The I/O mix of these types of databases is usually characterized by 75% to 90% random read and 25% to 10% write.
* Decision support system (DSS) databases can be also referred to as data warehouses. These databases are mission critical in many organizations that rely on analytics for their business. These databases are sensitive to CPU utilization and read operations from disk when queries are being run. In many organizations, DSS databases are the most critical during the month, quarter, and year end. This workload typically has a 100% read I/O mix.
