---
sidebar: sidebar
permalink: mssql/mssql-storage-efficiency.html
keywords: MSSQL,SQL Server, efficiency, compression, deduplication
summary: Microsoft SQL Server and ONTAP storage efficiency
searchtitle: Microsoft SQL Server and ONTAP storage efficiency
---
= Storage efficiency
:hardbreaks:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
ONTAP storage efficiency is optimized to store and manage SQL Server data in a way that consumes the least amount of storage space with no effect on performance. 

include::../_include/efficiency.adoc[]

include::../_include/compression.adoc[]

include::../_include/compaction.adoc[]

include::../_include/tsse.adoc[]

include::../_include/deduplication.adoc[]

include::../_include/efficiency-and-thin-provisioning.adoc[]

include::../_include/efficiency-bp.adoc[]

== Database compression

SQL Server itself also has features to compress and efficiently manage data. SQL Server currently supports two types of data compression: row compression and page compression. 

Row compression changes the data storage format. For example, it changes integers and decimals to the variable-length format instead of their native fixed-length format. It also changes fixed-length character strings to the variable-length format by eliminating blank spaces. Page compression implements row compression and two other compression strategies (prefix compression and dictionary compression). You can find more details about page compression in link:https://learn.microsoft.com/en-us/sql/relational-databases/data-compression/page-compression-implementation?view=sql-server-ver16&redirectedfrom=MSDN[Page Compression Implementation^]. 

Data compression is currently supported in the Enterprise, Developer, and Evaluation editions of SQL Server 2008 and later. Although compression can be performed by the database itself, this is rarely observed in a SQL Server environment.

Here are the recommendation for managing space for SQL Server data files

* Use thin provisioning in SQL Server environments to improve space utilization and to reduce the overall storage requirements when the space guarantee functionality is used.
- Use autogrow for most common deployment configurations because the storage admin only needs to monitor space usage in the aggregate.
* Do not enable deduplication on any volumes containing SQL Server data files unless the volume is known to contain multiple copies of the same data, such as restoring database from backups to a single volume.

== Space reclamation

Space reclamation can be initiated periodically to recover unused space in a LUN. With SnapCenter, you can use the following PowerShell command to start space reclamation. 
----
Invoke-SdHostVolumeSpaceReclaim -Path drive_path
----
If you need to run space reclamation, this process should be run during periods of low activity because it initially consumes cycles on the host.
