---
sidebar: sidebar
permalink: mssql/mssql-dr-smas-sql.html
keywords: MSSQL,SQL Server, SnapMirror active sync, ONTAP, SMBC, SMas, SnapMirror Business Continuity
summary: Microsoft SQL Server and SnapMirror active sync
---
= Microsoft SQL Server with SnapMirror active sync

[.lead]
Based on SQL Server deployment model and business requirement, SnapMirror active sync on ONTAP can be setup to achieve simplified disaster recovery solution.

== Standalone instance of SQL Server

SQL Server database could be hosted in a virtualized environment connected to storage via guest-connected iSCSI storage or a physical server connected to storage via iSCSI/FC-based protocol. The best practice for file layout and server configuration is the same as recommended in SQL Server ONTAP documentation. With a standalone setup, SQL Server would be running only at the primary site. 

* In a standalone instance setup, if only database data and log files are synchronously replicated to secondary storage, then in the event of a disaster, SnapMirror active sync will transparently failover from primary storage to secondary storage. In such a scenario of unexpected disaster, have an OS running at the remote site with a preconfigured SQL Server setup, updated with an equivalent build version as that of the production instance. Turn on the standalone instance of SQL Server at the secondary site and discover/mount the LUN. Bring the disk online and attach it to SQL Server. The complete process can be automated with the Windows Powershell cmdlet as no operations are required from the storage side.  
* If SQL Server data files reside on a virtual disk and are synchronously replicated to secondary storage along with virtual machines then in the event of a disaster, SnapMirror active sync will transparently failover from primary storage to secondary storage.  The administrator at the secondary site should discover and mount the datastore on a hypervisor (ESXi server or Hyper-V), turn on the virtual machine, and start the SQL Services.

== SQL Server failover cluster instance

SQL Server failover instance could be hosted on a Windows failover cluster running on a physical server or virtual server as the guest operating system. This multi-host architecture provides SQL Server instance and storage resiliency. Such deployment is helpful in high-demand environments seeking robust failover processes while maintaining enhanced performance. In a failover cluster setup, when a host or primary storage is affected then SQL Services will be failover to the secondary host, and at the same time, secondary storage will be available to serve the IO’s. No automation script or administrator intervention is required.  
