---
sidebar: sidebar
permalink: mssql/mssql-dr-smas-sql.html
keywords: MSSQL,SQL Server, SnapMirror active sync, ONTAP, SMBC, SMas, SnapMirror Business Continuity
summary: Microsoft SQL Server and SnapMirror active sync
---
= Microsoft SQL Server with SnapMirror active sync

[.lead]
Based on SQL Server deployment model and business requirement, SnapMirror active sync on ONTAP can be setup to achieve simplified disaster recovery solution.

== Standalone instance of SQL Server

SQL Server database could be hosted in virtualized environment, physical server connected via guest connected iSCSI storage or iSCSI/FC-based protocol respectively. Best practice for file layout and server configuration is same as recommended in SQL Server ONTAP documentation. With standalone setup setup, SQL Server would be running only at primary site. There could be multiple scenarios when disaster happens:

* In a standalone instance setup, if only database data and log files are synchronously replicated to secondary storage, then in event of disaster, SnapMirror active sync will transparently failover from primary storage to secondary storage. In such scenario of unexpected disaster, have a running OS at the remote site and it must be preconfigured with SQL Server setup and updated with equivalent build version as of production instance. Turn on the standalone instance of SQL Server at the secondary site and discover/mount the LUN.  Bring the disk online and attach it to SQL Server. Complete process can be automated with windows powershell cmdlet as no operations are required from storage side.  
* If SQL Server data files resides on virtual disk and synchronously replicated to secondary storage along with virtual machines then in event of disaster, SnapMirror active sync will transparently failover from primary storage to secondary storage. Administrator at the secondary site should discover and mount the datastore on hypervisor (ESXi server or Hyper-V) and turn on the virtual machine and start the SQL Services.

== SQL Server failover cluster instance

SQL Server failover instance could be hosted on Windows failover cluster running on physical server or virtual server as guest operating system. This multi-host architecture provides SQL Server instance and storage resiliency. Such deployment is helpfull in high-demand environments seeking robust failover process while maintaining enhance performance.In failover cluster setup, when host or primary storage are affected then SQL Services will be failover to secondary host and at the same time secondary storage will be available to serve the IO's.No automation script or administrator intervention is required.  
