---
sidebar: sidebar
permalink: mssql/mssql-dr-mcc-overview.html
keywords: MSSQL,SQL Server, MetroCluster, Disaster recovery
summary: Microsoft SQL Server and MetroCluster
---
= MetroCluster architecture
:imagesdir: ../media/

[.lead]
Understanding how Microsoft SQL Server operate in a MetroCluster environment requires some explanation of physical design of a MetroCluster system.

MetroCluster synchronously mirrors data and configuration between two ONTAP clusters in separate locations or failure domains. MetroCluster provides continuously available storage for applications by automatically managing two objectives:

• Zero recovery point objective (RPO) by synchronously mirroring data written to the cluster.
• Near zero recovery time objective (RTO) by mirroring configuration and automating access to data at the second site.

MetroCluster provides simplicity with automatic mirroring of data and configuration between the two independent clusters located in the two sites. As storage is provisioned within one cluster, it is automatically mirrored to the second cluster at the second site. NetApp SyncMirror® provides a complete copy of all data with a zero RPO. This means that workloads from one site could switch over at any time to the opposite site and continue serving data without data loss. MetroCluster manages the switchover process of providing access to NAS and SAN-provisioned data at the second site. The design of MetroCluster as a validated solution contains sizing and configuration that enables a switchover to be performed within the protocol timeout periods or sooner (typically less than 120 seconds). This results in a near zero RPO with the recovery for storage occurring within the storage
protocol timeout periods. Applications can continue accessing data without incurring failures.

MetroCluster is available in 3 variations defined by the back-end storage fabric. 

* HA pairs with IP connectivity
* HA pairs with FC connectivity
* Single controller with FC connectivity

include::../_include/metrocluster-physical-summary.adoc[]

Protection for SQL Server with MetroCluster is based on SyncMirror, which gives a maximum-performance, scale-out synchronous mirroring technology.
include::../_include/syncmirror-summary.adoc[]
