---
sidebar: sidebar
permalink: mssql/mssql-log-directory.html
keywords: MSSQL,SQL Server, volumes, LUN, SnapCenter
summary: Microsoft SQL Server log directory
searchtitle: Microsoft SQL Server log directory
---
= Log directory
:imagesdir: ../media/

[.lead]
The log directory is specified in SQL Server to store transaction log backup data at the host level. If you are using SnapCenter to backup log files then each SQL Server host used by SnapCenter must have a host log directory configured to perform log backups. SnapCenter has a database repository, so metadata related to backup, restore, or cloning operations is stored in a central database repository.

The sizes of the host log directory is calculated as follows:
Size of host log directory = ( (maximum DB LDF size x daily log change rate %) x (snapshot retention) รท (1 - LUN overhead space %)
The host log directory sizing formula assumes a 10% LUN overhead space

Place the log directory on a dedicated volume or LUN. The amount of data in the host log directory depends on the size of the backups and the number of days that backups are retained. SnapCenter allows only one host log directory per SQL Server host. You can configure the host log directories at SnapCenter --> Host --> Configure Plug-in.

[TIP]
====
*NetApp recommends* the following for a host log directory:

* Make sure that the host log directory is not shared by any other type of data that can potentially corrupt the backup snapshot data.
* Do not place user databases or system databases on a LUN that hosts mount points.
* Create the host log directory on a dedicated volume to which SnapCenter copies transaction logs.
* Use SnapCenter wizards to migrate databases to NetApp storage so that the databases are stored in valid locations, enabling successful SnapCenter backup and restore operations. Keep in mind that the migration process is disruptive and can cause the databases to go offline while the migration is in progress.
* The following conditions must be in place for failover cluster instances (FCIs) of SQL Server:
    - If you are using a failover cluster instance, the host log directory LUN must be a cluster disk resource in the same cluster group as the SQL Server instance being backed up SnapCenter.
    - If you are using a failover cluster instance, user databases must be placed on shared LUNs that are physical disk cluster resources assigned to the cluster group associated with the SQL Server instance.
====
