---
sidebar: sidebar
permalink: vmware/vmware-srm-deployment_best_practices.html
keywords: vmware, site, recovery manager, vsrm, svm, layout, segmentation, smt, best, practices, deploy, ontap, tools, vvols, srm, vlsr
summary: With ONTAP, the concept of the storage virtual machine (SVM) provides strict segmentation in secure multitenant environments.
---
= Deployment best practices
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The following sections outline the deployment best practices with ONTAP and VMware SRM.

== Use the latest version of ONTAP tools 10

ONTAP tools 10 provides significant improvements over previous versions, including the following:

* 8x faster test failover*
* 2x faster cleanup and reprotect*
* 32% faster failover*
* Greater scale
* Native support for shared site layouts

*These improvements are based on internal testing and may vary based on your environment.

== SVM layout and segmentation for SMT

With ONTAP, the concept of the storage virtual machine (SVM) provides strict segmentation in secure multitenant environments. SVM users on one SVM cannot access or manage resources from another. In this way, you can leverage ONTAP technology by creating separate SVMs for different business units who manage their own SRM workflows on the same cluster for greater overall storage efficiency.

Consider managing ONTAP using SVM-scoped accounts and SVM management LIFs to not only improve security controls, but also improve performance. Performance is inherently greater when using SVM-scoped connections because the SRA is not required to process all the resources in an entire cluster, including physical resources. Instead, it only needs to understand the logical assets that are abstracted to the particular SVM.

//== Deploy ONTAP tools and considerations for vVols
//
//If you intend to use SRM with vVols, you must manage the storage using cluster- scoped credentials and a cluster management LIF. This is because the VASA Provider must understand the underlying physical architecture to satisfy the policy requires for VM storage policies. For example, if you have a policy that requires all- flash storage, the VASA Provider must be able to see which systems are all flash.

//Another deployment best practice is to never store your ONTAP tools appliance on a vVols datastore that it is managing. This could lead to a situation whereby you cannot power on the VASA Provider because you cannot create the swap vVol for the appliance because the appliance is offline.

== Best practices for managing ONTAP 9 systems

As previously mentioned, you can manage ONTAP clusters using either cluster or SVM scoped credentials and management LIFs. For optimum performance, you may want to consider using SVM- scoped credentials whenever you aren't using vVols. However, in doing so, you should be aware of some requirements, and that you do lose some functionality.

* The default vsadmin SVM account does not have the required access level to perform ONTAP tools tasks. Therefore, you need to create a new SVM account. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-user-role-and-privileges.html[Configure ONTAP user roles and privileges] using the included JSON file. This can be used for SVM or cluster scoped accounts.
+
* Because the vCenter UI plugin, VASA Provider, and SRA server are all fully integrated microservices, you must add storage to the SRA adapter in SRM the same way you add storage in the vCenter UI for ONTAP tools. Otherwise, the SRA server might not recognize the requests being sent from SRM via the SRA adapter.
* NFS path checking is not performed when using SVM-scoped credentials unless you first https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html[onboard clusters] in ONTAP tools manager and associate them with vCenters. This is because the physical location is logically abstracted from the SVM. This is not a cause for concern though, as modern ONTAP systems no longer suffer any noticeable performance decline when using indirect paths.
* Aggregate space savings due to storage efficiency might not be reported.
* Where supported, load-sharing mirrors cannot be updated.
* EMS logging might not be performed on ONTAP systems managed with SVM scoped credentials.
