---
sidebar: sidebar
permalink: vmware/vmware-vsphere-network.html
keywords: vSphere, datastore, VMFS, FC, FCoE, NVMe/FC, iSCSI, NFS, vVols
summary: This page describes the best practices for implementing a ONTAP storage solution in a VMware vSphere environment.
---
= Network configuration
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Configuring network settings when using vSphere with systems running ONTAP is straightforward and similar to other network configuration. 

Here are some things to consider:

* Separate storage network traffic from other networks. A separate network can be achieved by using a dedicated VLAN or separate switches for storage. If the storage network shares physical paths such as uplinks, you might need QoS or additional uplink ports to make sure of sufficient bandwidth. Don't connect hosts directly to storage; use switches to have redundant paths and allow VMware HA to work without intervention. See link:vmware-vsphere-network.html[Direct connect networking] for additional information.
* Jumbo frames can be used if desired and supported by your network, especially when using iSCSI. If they are used, make sure they are configured identically on all network devices, VLANs, and so on in the path between storage and the ESXi host. Otherwise, you might see performance or connection problems. The MTU must also be set identically on the ESXi virtual switch, the VMkernel port, and also on the physical ports or interface groups of each ONTAP node.
* NetApp only recommends disabling network flow control on the cluster network ports within an ONTAP cluster. NetApp makes no other recommendations for best practices for the remaining network ports used for data traffic. You should enable or disable it as necessary. See https://www.netapp.com/pdf.html?item=/media/16885-tr-4182pdf.pdf[TR-4182^] for more background on flow control.
* When ESXi and ONTAP storage arrays are connected to Ethernet storage networks, NetApp recommends configuring the Ethernet ports to which these systems connect as Rapid Spanning Tree Protocol (RSTP) edge ports or by using the Cisco PortFast feature. NetApp recommends enabling the Spanning-Tree PortFast trunk feature in environments that use the Cisco PortFast feature and that have 802.1Q VLAN trunking enabled to either the ESXi server or the ONTAP storage arrays.
* NetApp recommends the following best practices for link aggregation:
** Use switches that support link aggregation of ports on two separate switch chassis using a multi-chassis link aggregation group approach such as Cisco's Virtual PortChannel (vPC).
** Disable LACP for switch ports connected to ESXi unless you are using dvSwitches 5.1 or later with LACP configured.
** Use LACP to create link aggregates for ONTAP storage systems with dynamic multimode interface groups with IP hash.
** Use an IP hash teaming policy on ESXi.

The following table provides a summary of network configuration items and indicates where the settings are applied.

|===
|Item |ESXi |Switch |Node |SVM

|IP address
|VMkernel
|No**
|No**
|Yes
|Link aggregation
|Virtual switch
|Yes
|Yes
|No*
|VLAN
|VMkernel and VM port groups
|Yes
|Yes
|No*
|Flow control
|NIC
|Yes
|Yes
|No*
|Spanning tree
|No
|Yes
|No
|No
|MTU (for jumbo frames)
|Virtual switch and VMkernel port (9000)
|Yes (set to max)
|Yes (9000)
|No*
|Failover groups
|No
|No
|Yes (create)
|Yes (select)
|===

*SVM LIFs connect to ports, interface groups, or VLAN interfaces that have VLAN, MTU, and other settings. However, the settings are not managed at the SVM level.

**These devices have IP addresses of their own for management, but these addresses are not used in the context of ESXi storage networking.

== SAN (FC, FCoE, NVMe/FC, iSCSI), RDM

ONTAP provides enterprise-class block storage for VMware vSphere using traditional iSCSI and Fibre Channel Protocol(FCP, or FC for short), and the incredibly performant and CPU efficient next-generation block protocol NVMe over Fabrics (NVMe-oF); with both NVMe/FC and NVMe/TCP support. For detailed best practices for implementing block protocols for VM storage with vSphere and ONTAP refer to link:vmware-vsphere-datastores-nfs.html[Datastores and Protocols - SAN]

== NFS
vSphere allows customers to use enterprise-class NFS arrays to provide concurrent access to datastores to all the nodes in an ESXi cluster. As mentioned in the link:vmware-vsphere-datastores-top.html[datastores] section, there are some ease of use and storage efficiency visibility benefits when using NFS with vSphere.

For recommended best practices refer to link:vmware-vsphere-datastores-nfs.html[Datastores and Protocols - NFS]

== Direct connect networking

Storage administrators sometimes prefer to simplify their infrastructures by removing network switches from the configuration. This can be supported in some scenarios.

=== iSCSI and NVMe/TCP

A host using iSCSI or NVMe/TCP can be directly connected to a storage system and operate normally. The reason is pathing. Direct connections to two different storage controllers result in two independent paths for data flow. The loss of path, port, or controller does not prevent the other path from being used. 

=== NFS

Direct-connected NFS storage can be used, but with a significant limitation - failover will not work without a significant scripting effort, which would be the responsibility of the customer. 

The reason nondisruptive failover is complicated with direct-connected NFS storage is the routing that occurs on the local OS. For example, assume a host has an IP address of 192.168.1.1/24 and is directly connected to an ONTAP controller with an IP address of 192.168.1.50/24. During failover, that 192.168.1.50 address can fail over to the other controller, and it will be available to the host, but how does the host detect its presence? The original 192.168.1.1 address still exists on the host NIC that no longer connects to an operational system. Traffic destined for 192.168.1.50 would continue to be sent to an inoperable network port.

The second OS NIC could be configured as 19     2.168.1.2 and would be capable of communicating with the failed over 192.168.1.50 address, but the local routing tables would have a default of using one *and only one* address to communicate with the 192.168.1.0/24 subnet. A sysadmin could create a scripting framework that would detect a failed network connection and alter the local routing tables or bring interfaces up and down. The exact procedure would depend on the OS in use. 

In practice, NetApp customers do have direct-connected NFS, but normally only for workloads where IO pauses during failovers are acceptable. When hard mounts are used, there should not be any IO errors during such pauses. The IO should hang until services are restored, either by a failback or manual intervention to move IP addresses between NICs on the host.

=== FC Direct Connect

It is not possible to directly connect a host to an ONTAP storage system using the FC protocol. The reason is the use of NPIV. The WWN that identifies an ONTAP FC port to the FC network uses a type of virtualization called NPIV. Any device connected to an ONTAP system must be able to recognize an NPIV WWN. There are no current HBA vendors who offer an HBA that can be installed in a host that would be able to support an NPIV target. 

