---
sidebar: sidebar
permalink: vmware/vmware-otv-hardening-access.html
keywords: VMware, Data protection, security, ONTAP tools, Hardening, ONTAP Tools
summary: Security Hardening Guide for ONTAP tools for VMware vSphere.
---
= ONTAP tools for VMware vSphere access points (Users) 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The ONTAP Tools for VMware vSphere installation creates and uses below four types of users:

[arabic]
. System User (root user)
. Application user (administrator user, maint user, db user)
. Support user(diag user)

== 1. System User

System(root) user gets created by ONTAP tools installation on underlying operating system(debian).

* A default system user "root" is created on Debian by ONTAP tools installation. Its default disabled and can be enabled on ad hoc basis through the 'maint' console.

== 2. Application User

Application user is named as local user in ONTAP tools. These are users created in ONTAP tools application. Below table lists the types of Application users:

[width="100%",cols="22%,78%",options="header",]
|===
|*User* |*Description*
|Administrator User |It is created during ONTAP tools installation and user provides the credentials while deploying the ONTAP tools. Users has the option to change the 'password' in 'maint' console. Password will expire in 90 days and users are expected to change the same.
|Maintenance User |It is created during ONTAP tools installation and user provides the credentials while deploying the ONTAP tools. Users has the option to change the 'password' in 'maint' console. This is maintenance user and is created to execute the maintenance console operations.
|Database User |It is created during ONTAP tools installation and user provides the credentials while deploying the ONTAP tools. Users has the option to change the 'password' in 'maint' console. Password will expire in 90 days and users are expected to change the same.
|===

== 3. Support user(diag user)

Support user as well created during ONTAP tools installation and is used to access the machine and collect logs in case of any issue/outage in the server. Default its disabled and can be enabled on ad hoc basis through 'maint' console. It will auto disable after a certain time period.