---
sidebar: sidebar
permalink: vmware/vmware-vsphere-network.html
keywords: vSphere, datastore, VMFS, FC, FCoE, NVMe-FC, iSCSI, NFS, vVols
summary: This page describes the best practices for implementing a ONTAP storage solution in a VMware vSphere environment.
---
= Network configuration
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Configuring network settings when using vSphere with systems running ONTAP is straightforward and similar to other network configuration. 

Here are some things to consider:

* Separate storage network traffic from other networks. A separate network can be achieved by using a dedicated VLAN or separate switches for storage. If the storage network shares physical paths such as uplinks, you might need QoS or additional uplink ports to make sure of sufficient bandwidth. Don't connect hosts directly to storage unless your solution guide specifically calls for it; use switches to have redundant paths and allow VMware HA to work without intervention. 
* Jumbo frames should be used if supported by your network. If they are used, make sure they are configured identically on all network devices, VLANs, and so on in the path between storage and the ESXi host. Otherwise, you might see performance or connection problems. The MTU must also be set identically on the ESXi virtual switch, the VMkernel port, and also on the physical ports or interface groups of each ONTAP node.
* NetApp only recommends disabling network flow control on the cluster-interconnect ports within an ONTAP cluster. NetApp makes no other recommendations for best practices regarding flow control for the remaining network ports used for data traffic. You should enable or disable it as necessary. See https://www.netapp.com/pdf.html?item=/media/16885-tr-4182pdf.pdf[TR-4182^] for more background on flow control.
* When ESXi and ONTAP storage arrays are connected to Ethernet storage networks, NetApp recommends configuring the Ethernet ports to which these systems connect as Rapid Spanning Tree Protocol (RSTP) edge ports or by using the Cisco PortFast feature. NetApp recommends enabling the Spanning-Tree PortFast trunk feature in environments that use the Cisco PortFast feature and that have 802.1Q VLAN trunking enabled to either the ESXi server or the ONTAP storage arrays.
* NetApp recommends the following best practices for link aggregation:
** Use switches that support link aggregation of ports on two separate switch chassis using a multi-chassis link aggregation group approach such as Cisco's Virtual PortChannel (vPC).
** Disable LACP for switch ports connected to ESXi unless you are using dvSwitches 5.1 or later with LACP configured.
** Use LACP to create link aggregates for ONTAP storage systems with dynamic multimode interface groups with IP hash.
** Use an IP hash teaming policy on ESXi.

The following table provides a summary of network configuration items and indicates where the settings are applied.

|===
|Item |ESXi |Switch |Node |SVM

|IP address
|VMkernel
|No**
|No**
|Yes
|Link aggregation
|Virtual switch
|Yes
|Yes
|No*
|VLAN
|VMkernel and VM port groups
|Yes
|Yes
|No*
|Flow control
|NIC
|Yes
|Yes
|No*
|Spanning tree
|No
|Yes
|No
|No
|MTU (for jumbo frames)
|Virtual switch and VMkernel port (9000)
|Yes (set to max)
|Yes (9000)
|No*
|Failover groups
|No
|No
|Yes (create)
|Yes (select)
|===

*SVM LIFs connect to ports, interface groups, or VLAN interfaces that have VLAN, MTU, and other settings. However, the settings are not managed at the SVM level.

**These devices have IP addresses of their own for management, but these addresses are not used in the context of ESXi storage networking.

== SAN (FC, NVMe/FC, iSCSI, NVMe/TCP), RDM

ONTAP offers enterprise-class block storage for VMware vSphere using traditional iSCSI and Fibre Channel Protocol (FCP) as well as the highly efficient and performant next-generation block protocol, NVMe over Fabrics (NVMe-oF), with support for both NVMe/FC and NVMe/TCP.

For detailed best practices for implementing block protocols for VM storage with vSphere and ONTAP refer to link:vmware-vsphere-datastores-san.html[Datastores and Protocols - SAN]

== NFS
vSphere allows customers to use enterprise-class NFS arrays to provide concurrent access to datastores to all the nodes in an ESXi cluster. As mentioned in the link:vmware-vsphere-datastores-top.html[datastores] section, there are some ease of use and storage efficiency visibility benefits when using NFS with vSphere.

For recommended best practices refer to link:vmware-vsphere-datastores-nfs.html[Datastores and Protocols - NFS]

== Direct connect networking

Virtualization administrators sometimes prefer to simplify their infrastructures by removing network switches from the configuration. This allows creation of a more self-contained solution with fewer components and less space required in the rack. There are some important restrictions that depend on the protocol in use.

include::../_include/direct-connect.adoc[]