---
sidebar: sidebar
permalink: vmware/vmware-vsphere-overview.html
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud
summary: ONTAP has been a leading storage solution for VMware vSphere environments for almost two decades and continues to add innovative capabilities to simplify management while reducing costs. This document introduces the ONTAP solution for vSphere, including the latest product information and best practices, to streamline deployment, reduce risk, and simplify management.
---
= VMware vSphere with ONTAP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
ONTAP has served as a premier storage solution for VMware vSphere and, more recently, Cloud Foundation environments since its introduction into the modern datacenter in 2002. It continues to introduce innovative features that simplify management and lower costs.

This document presents the ONTAP solution for vSphere, highlighting the latest product information and best practices to streamline deployment, mitigate risks, and simplify management.

[NOTE]
This documentation replaces previously published technical reports _TR-4597: VMware vSphere for ONTAP_

Best practices supplement other documents such as guides and compatibility lists. They are developed based on lab testing and extensive field experience by NetApp engineers and customers. They might not be the only supported practices that work in every environment, but they are generally the simplest solutions that meet the needs of most customers.

This document is focused on capabilities in recent releases of ONTAP (9.x) running on vSphere 7.0 or later. See the https://imt.netapp.com/matrix/#search[Interoperability Matrix Tool (IMT)^] and https://www.vmware.com/resources/compatibility/search.php?deviceCategory=san[VMware Compatibility Guide^] for details related to specific releases.
