---
sidebar: sidebar
permalink: vmware/vmware-vsphere-why.html
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud
summary: Customers confidently select ONTAP for vSphere due to its unified SAN and NAS storage solutions and the new simplified disaggregated storage architecture, which is featured in the latest All SAN Arrays. This platform provides exceptional snapshot protection and robust management tools. By offloading functions to dedicated storage, ONTAP maximizes host resources, reduces costs, and maintains optimal performance. Additionally, workloads can be easily migrated using Storage vMotion across VMFS, NFS, or vVols.
---
= Why ONTAP for VMware vSphere?
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Customers confidently select ONTAP for vSphere for both SAN and NAS storage solutions.The new simplified disaggregated storage architecture, which is featured in the latest All SAN Arrays, delivers a simplified experience familiar to SAN storage administrators while keeping most of the integrations and feature set of traditional ONTAP systems. ONTAP systems provide exceptional snapshot protection and robust management tools. By offloading functions to dedicated storage, ONTAP maximizes host resources, reduces costs, and maintains optimal performance. Additionally, workloads can be easily migrated using Storage vMotion across VMFS, NFS, or vVols.

== The advantages of using ONTAP for vSphere
There are many reasons why tens of thousands of customers have selected ONTAP as their storage solution for vSphere, such as a unified storage system supporting both SAN and NAS protocols, robust data protection capabilities using space-efficient snapshots and a wealth of tools to help you manage application data. Using a storage system separate from the hypervisor allows you to offload many functions and maximize your investment in vSphere host systems. This approach not only makes sure your host resources are focused on application workloads, but it also avoids random performance effects on applications from storage operations.

Using ONTAP together with vSphere is a great combination that lets you reduce host hardware and VMware software expenses. You can also protect your data at lower cost with consistent high performance. Because virtualized workloads are mobile, you can explore different approaches using Storage vMotion to move VMs across VMFS, NFS, or vVols datastores, all on the same storage system.

Here are key factors customers value today:

* *Unified storage.* Systems running ONTAP are unified in several significant ways. Originally this approach referred to both NAS and SAN protocols, and ONTAP continues to be a leading platform for SAN along with its original strength in NAS. In the vSphere world, this approach could also mean a unified system for virtual desktop infrastructure (VDI) together with virtual server infrastructure (VSI). Systems running ONTAP are typically less expensive for VSI than traditional enterprise arrays and yet have advanced storage efficiency capabilities to handle VDI in the same system. ONTAP also unifies a variety of storage media, from SSDs to SATA, and can extend that easily into the cloud. There's no need to buy one storage operating system for performance, another for archives, and yet another one for the cloud. ONTAP ties them all together.
* *All SAN Array (ASA).* The latest ONTAP ASA systems (beginning with the A1K, A90, A70, A50, A30, and A20) are built on a new storage architecture that eliminates the traditional ONTAP storage paradigm of managing aggregates and volumes. Since there are no file system shares, there's no need for volumes! All storage attached to an HA pair is treated as a common Storage Availability Zone (SAZ) within which LUNs and NVMe namespaces are provisioned as "Storage Units" (SUs). The latest ASA systems are designed to be simple to manage, with a familiar experience for SAN storage administrators. This new architecture is ideal for vSphere environments, as it allows for easy management of storage resources and provides a simplified experience for SAN storage administrators. The ASA architecture also supports the latest NVMe over Fabrics (NVMe-oF) technology, which provides even greater performance and scalability for vSphere workloads.
* *Snapshot technology.* ONTAP was the first to deliver snapshot technology for data protection, and it remains the most advanced in the industry. This space-efficient approach to data protection has been extended to support VMware vSphere APIs for Array Integration (VAAI). This integration allows you to take advantage of ONTAP's snapshot capabilities for backup and restore operations, reducing the impact on your production environment. This approach also allows you to use snapshots for rapid recovery of VMs, reducing the time and effort required to restore data. In addition, ONTAP's snapshot technology is integrated with VMware's Live Site Recovery (VLSR, formerly Site Recovery Manager [SRM]) solutions, providing a comprehensive data protection strategy for your virtualized environment.
* *Virtual volumes and storage policy based management.* NetApp was an early design partner with VMware in the development of vSphere Virtual Volumes (vVols), providing architectural input and early support for vVols and VMware vSphere APIs for Storage Awareness (VASA). Not only did this approach bring granular VM storage management to VMFS, it also supported automation of storage provisioning through storage policy based management. This approach allows storage architects to design storage pools with different capabilities that can be easily consumed by VM administrators. ONTAP leads the storage industry in vVol scale, supporting hundreds of thousands of vVols in a single cluster, whereas enterprise array and smaller flash array vendors support as few as several thousand vVols per array. NetApp is also driving the evolution of granular VM management with upcoming capabilities.
* *Storage efficiency.* Although NetApp was the first to deliver deduplication for production workloads, this innovation wasn't the first or last one in this area. It started with snapshots, a space-efficient data protection mechanism with no performance effect, along with FlexClone technology to instantly make read/write copies of VMs for production and backup use. NetApp went on to deliver inline capabilities, including deduplication, compression, and zero-block deduplication, to squeeze out the most storage from expensive SSDs. ONTAP also added the ability to pack smaller I/O operations and files into a disk block using compaction. The combination of these capabilities has resulted in customers commonly seeing savings of up to 5:1 for VSI and up to 30:1 for VDI. The newest generation of ONTAP systems also include hardware-accelerated compression and deduplication, which can further improve storage efficiency and reduce costs. This approach allows you to store more data in less space, reducing the overall cost of storage and improving performance. NetApp is so confident in its storage efficiency capabilities that it offers an link:https://www.netapp.com/pdf.html?item=/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf
[Efficiency Guarantee^].
* *Multitenancy.* ONTAP has long been a leader in multitenancy, allowing you to create multiple storage virtual machines (SVMs) on a single cluster. This approach allows you to isolate workloads and provide different levels of service to different tenants, making it ideal for service providers and large enterprises. The latest generation of ONTAP systems also includes support tenent capacity management. This feature allows you to set capacity limits for each tenant, ensuring that no single tenant can consume all the available resources. This approach helps to ensure that all tenants receive the level of service they expect, while also providing a high level of security and isolation between tenants. In addition, ONTAP's multitenancy capabilities are integrated with VMware's vSphere platform, allowing you to easily manage and monitor your virtualized environment through https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html[ONTAP tools for VMware vSphere] and https://docs.netapp.com/us-en/data-infrastructure-insights/[Data Infrastructure Insights].
* *Hybrid cloud.* Whether used for on-premises private cloud, public cloud infrastructure, or a hybrid cloud that combines the best of both, ONTAP solutions help you build your data fabric to streamline and optimize data management. Start with high-performance all-flash systems, then couple them with either disk or cloud storage systems for data protection and cloud compute. Choose from Azure, AWS, IBM, or Google clouds to optimize costs and avoid lock-in. Leverage advanced support for OpenStack and container technologies as needed. NetApp also offers cloud-based backup (SnapMirror Cloud, Cloud Backup Service, and Cloud Sync) and storage tiering and archiving tools (FabricPool) for ONTAP to help reduce operating expenses and leverage the broad reach of the cloud.
* *And more.* Take advantage of the extreme performance of NetApp AFF A-Series arrays to accelerate your virtualized infrastructure while managing costs. Enjoy completely nondisruptive operations, from maintenance to upgrades to complete replacement of your storage system, using scale-out ONTAP clusters. Protect data at rest with NetApp encryption capabilities at no additional cost. Make sure performance meets business service levels through fine-grained quality of service capabilities. They are all part of the broad range of capabilities that come with ONTAP, the industry's leading enterprise data management software.
