---
sidebar: sidebar
permalink: vmware/vmware-otv-hardening-login-banner.html
keywords: VMware, Data protection, security, OTV, Hardening, ONTAP Tools
summary: Security Hardening Guide for ONTAP tools for VMware vSphere, login banner.
---
= Login Banner 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The following login banner is shown after the user enters a username in the login prompt. Please note that SSH is disabled by default and only allows one-time logins when enabled from the VM console. 

 WARNING: Unauthorized access to this system is forbidden and will be
 prosecuted by law. By accessing this system, you agree that your actions
 may be monitored if unauthorized usage is suspected.

After the user completes login through the SSH channel, the following text is displayed:

 Linux UnifiedVSC 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64
 
 The programs included with the Debian GNU/Linux system are free software;
 the exact distribution terms for each program are described in the
 individual files in /usr/share/doc/*/copyright.

 Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
 permitted by applicable law.