---
sidebar: sidebar
permalink: epic/epic-config-filesystems.html
keywords: epic,cache,iris
summary: Epic on ONTAP is awesome
---

= >>> Level One Title

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media

[.lead]
>>> Placeholder for descriptive lead sentence or paragraph

Mount options

Asynchronous I/O

A copy of the Epic SAN Considerations whitepaper and the Storage Configuration Quick Reference document provide details about how to configure the hosts and connect to storage. This section reviews how to set up a Red Hat Enterprise Linux host. AIX details can be found in the referenced documents.

File system and mount options

For information about mounting LUNs, creating volume groups and logical volumes, and configuring the file systems, see the Epic Storage Configuration Quick Reference Guide. Use the following sample commands to set up Epic Production servers for RHEL.

After the LUNs have been created and mapped, and the zoning is complete, use the following procedure to attach storage to the server. 

Note: In this example, we used 8x 1024Gb LUNs for the DB, 2x 1024Gb LUNs for journals, and 2x 1024Gb LUNs for application installations.

