---
sidebar: sidebar
permalink: epic/epic-config-performance.html
keywords: epic,cache,iris
summary: Epic performance management
---

= Epic performance management

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Most all-flash arrays can deliver the performance required for Epic workloads. The NetApp differentiator is its ability to set floor level performance policies and guarantee a consistent performance for each application.

== Adaptive QoS

NetApp recommends using Adaptive QoS (AQoS). The benefit of AQoS is the ability to consolidate all Epic workloads. All protocols and pools of storage can reside on less hardware. You do not need to separate pools of storage.

* NetApp recommends accepting SLM recommended performance policy for at least Production ODB, Report, and Clarity when consolidating Epic workloads and stay compliant with Epic recommendations.

* NetApp recommends having all workloads in the cluster assigned to a policy by SLM to better manage headroom on the cluster.

* NetApp recommends balancing all workloads evenly across the HA pair.

* Do not use QOS policies when performing any I/O testing. Only assign policies after SLM has analyzed real production data; otherwise, GenIO testing will fail. Allow SLM to analyze the production workloads for 2-4 weeks before assigning any recommended policies.

//chrisgeb - revisit this page as Mike may want to update these recommendations as NSLM is no longer.