---
sidebar: sidebar
permalink: epic/epic.introduction.html
keywords: epic,cache,iris
summary: Epic on ONTAP is awesome
---

= >>> Level One Title

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media

[.lead]
>>> Placeholder for descriptive lead sentence or paragraph

= Introduction

The key to digital transformation is simply doing more with data. Hospitals require large amounts of data to start the journey of digital transformation. Part of the process of treating patients, managing staff schedules and medical resources is that information is collected and processed. However, these events still happen manually or through outdated systems. The one constant is that the amount of data continues to grow exponentially and thus, becomes increasingly difficult to manage.

The major cause of this problem with hospitals is that data is often held in data silos. Too much time is spent on manual entries and updates which lead to burnout and errors. This document is about one part of healthcare data, specifically Epic Electronic Health Records (EHR). However, this data management strategy can and should be applied to all healthcare data. Partner with NetApp’s extensive healthcare team with a proven history of modernizing and simplifying digital infrastructure. Our data fabric forms the building block of digital transformation. 

NetApp offers a single data management solution for all healthcare needs, and we are able to guide hospitals through their journey toward digital transformation. Building a foundation with structure and smart solutions, healthcare can extract the full value of this precious information. This framework can help medical providers diagnose diseases faster and develop individualized treatment plans to better support decision-making processes in emergency situations. You will also be able to build your own data fabric and enable your hospital to unlock data silos, facilitate data interoperability, and protect sensitive patient information. 

Use this document as a guide to successfully construct and implement Epic EHR. Rather than building multiple Epic silos, build Epic on your new data fabric and transform your hospital.
