---
sidebar: sidebar
permalink: epic/epic-sizing-6node.html
keywords: epic,cache,iris
summary: Epic on ONTAP is awesome
---

= >>> Level One Title

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media

[.lead]
>>> Placeholder for descriptive lead sentence or paragraph

= Eight-node architecture

Figure 11 shows the scale-out eight-node architecture. Again, you can start with four node and scale to six nodes and continue to scale to eight nodes and beyond. This architecture offers the best balance of performance and capacity across the six nodes in production.

The test environments are cloned from Report instead of Production in this design. This offloads test environments and integrity checks from production.

Figure 11) Eight-node architecture.



Figure 12 describes the workload placement in more detail for a four-node design.

Figure 12) Eight-node, high-level storage design and layout.
tecture.



Figure 10 describes the workload placement in more detail for a six-node design.

Figure 10) Six-node, high-level storage design and layout.
