---
sidebar: sidebar
permalink: epic/epic-overview.html
keywords: epic,cache,iris
summary: Epic on ONTAP overview
---

= Epic on ONTAP

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media

[.lead]
The key to digital transformation is simply doing more with data. Hospitals require large amounts of data to start the journey of digital transformation.

Part of the process of treating patients, managing staff schedules and medical resources is that information is collected and processed. However, these events still happen manually or through outdated systems. The one constant is that the amount of data continues to grow exponentially and thus, becomes increasingly difficult to manage.

The major cause of this problem with hospitals is that data is often held in data silos. Too much time is spent on manual entries and updates which lead to burnout and errors. This document is about one part of healthcare data, specifically Epic Electronic Health Records (EHR). However, this data management strategy can and should be applied to all healthcare data. Partner with NetApp’s extensive healthcare team with a proven history of modernizing and simplifying digital infrastructure. Our data fabric forms the building block of digital transformation. 

NetApp offers a single data management solution for all healthcare needs, and we are able to guide hospitals through their journey toward digital transformation. Building a foundation with structure and smart solutions, healthcare can extract the full value of this precious information. This framework can help medical providers diagnose diseases faster and develop individualized treatment plans to better support decision-making processes in emergency situations. You will also be able to build your own data fabric and enable your hospital to unlock data silos, facilitate data interoperability, and protect sensitive patient information. 

Use this document as a guide to successfully construct and implement Epic EHR. Rather than building multiple Epic silos, build Epic on your new data fabric and transform your hospital.

== Purpose

This document describes best practices for integrating NetApp storage into an Epic software environment. It contains the following sections:

* Epic overview offers NetApp field engineers a technical understanding of the Epic software environment and its storage requirements across various configurations.
* Epic storage considerations describes important decision-making storage factors when architecting an Epic solution, NetApp reference architecture, and sizing.
* NetApp AFF overview describes important features of the NetApp AFF solution.
* NetApp storage recommendations describes NetApp storage configuration best practices for satisfying Epic storage requirements.
* Integration tuning describes the host-side tuning required by Epic to enable the software to best integrate with NetApp storage.

== Scope

The NetApp storage best practices provided in this document apply to environments with the following characteristics:

* Environments that use the NetApp ONTAP® software version 9.4 and later. NetApp Service Level Manager (SLM) and Adaptive Quality of Service (AQoS) should be used.

* Disaster recovery capabilities.

This document does not cover the following subjects:

* Quantitative performance requirements and sizing guidance, which are addressed in TR-3930i: NetApp Sizing Guidelines for Epic (NetApp login required).

== Audience

This document is intended for NetApp, partner solutions engineers (SEs), and professional services personnel. NetApp assumes that the reader has the following background knowledge:

* A solid understanding of SAN and NAS concepts
* Technical familiarity with NetApp ONTAP storage systems
* Technical familiarity with the configuration and administration of ONTAP software
