---
sidebar: sidebar
permalink: epic/epic-ontap-consolidation.html
keywords: epic,cache,iris
summary: Epic on ONTAP is awesome
---

= >>> Level One Title

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media

[.lead]
>>> Placeholder for descriptive lead sentence or paragraph

= Consolidation or workload isolation?

Consolidating workloads into a single platform to improve efficiency is the goal of most organizations. Epic recommends each storage pool to be on separate physical hardware, pool1, pool2, pool3, NAS1, and NAS2. The main reason for these silos is to protect critical workload performance such as Epic Production, Report, and Clarity from contention and disruption to patient care. Performance issues are the same as an outage.

NetApp can guarantee performance of all workloads with Service Level Manager (SLM). This capability provides consistent guaranteed floor-level performance based on IOPs/TB. With AQoS, you can consolidate all workloads onto less hardware (on a single cluster, that is) and simplify storage with more efficiency.

Active IQ Unified Manger comes with the SLM and constantly monitors all workloads using machine learning. After 24 hours, SLM starts recommending performance policies for all workloads. Simply assign the recommended policy and lock in a floor-level performance. Protected workloads are automatically allocated performance headroom as they grow based on IOPs/TB. The SLM dashboard reports on each workload on the cluster and details on the cluster capacity and performance headroom.

Provision new workloads with a service level to the cluster with no fear of contention with existing workloads. The SLM verifies headroom is available and automatically places the workload in the cluster. The SLM can be managed with REST APIs and can integrate into automated service-level provisioning like Service Now.
