---
sidebar: sidebar
permalink: epic/epic-ontap-dp.html
keywords: epic,cache,iris
summary: Epic data protection
---

= Epic data protection

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media

[.lead]

Epic recognizes that the storage node-based NetApp Snapshot technology has no performance effect on production workloads compared to traditional file-based backups. When Snapshot backups are used as a recovery source for the production database, the backup method must be implemented with database consistency in mind.

A snapshot is a point-in-time, read-only backup copy of a volume. NetApp FlexClone® takes a Snapshot copy and makes it instantly read and writable. FlexClone volumes provide great value, taking read-only, application-consistent Snapshot copies and creating writable FlexClone volumes from production data. This native capability has a significant impact on storage savings, operations time, and automation capabilities.

For the refresh process, FlexClone volumes are used. 

== Data management

As part of the solution, NetApp delivers a fully automated backup and test refresh solution by using native ONTAP tools. This solution was designed to simplify Epic data management specifically for the large community of Epic database administrators (DBAs):

* Epic Mirror is used to replicate data to disaster recovery and Report (indicated with green).

* Daily data dumps from Report to Clarity. 

* NetApp automated backups (indicated with yellow).

* NetApp automated test refresh of SUP, REP, and other (indicated with blue).

* The test environments are for full-copy environments, not smaller squash copies.

For more information, reach out to NetApp Services for Epic applications.
