---
sidebar: sidebar
permalink: epic/epic-additional-info.html
keywords: epic,cache,iris
summary: Additional information for Epic on ONTAP
---

= Additional information for Epic on ONTAP

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media

[.lead]
To learn more about the information described in this document, refer to the following documents and/or websites:

* NetApp Product Documentation

https://www.netapp.com/us/documentation/index.aspx 

* ONTAP 9 Documentation Center

https://docs.netapp.com/ontap-9/index.jsp 

* Consistency Groups

https://docs.netapp.com/us-en/ontap/consistency-groups/#learn-about-consistency-groups 

* ONTAP and ONTAP System Manager Documentation Resources 

https://www.netapp.com/us/documentation/ontap-and-oncommand-system-manager.aspx 

* TR-3930i: NetApp Sizing Guidelines for Epic (NetApp login required) 

https://fieldportal.netapp.com/content/192412?assetComponentId=192510 

Epic Customer Guidance documents

Epic provides customers the following documents to its customers for guidance on server, storage, and network. These documents are referenced in this technical report.

* Storage Area Network Considerations

* Business Continuity Technical Solutions Guide

* All-Flash Reference Architecture Strategy Handbook

* Storage Products and Technology Status 

* Epic Cloud Considerations 

* Hardware Configuration Guide (customer-specific)

* Database Storage Layout Recommendations (customer-specific)

