---
sidebar: sidebar
permalink: epic/epic-arch-storage.html
keywords: epic,cache,iris
summary: Epic storage requirements
---

= Epic storage requirements

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Dedicated storage resources are generally provided for the production database, whereas mirror database instances share secondary storage resources with other Epic software-related components, such as the Clarity reporting tools.

Other software storage environments, such as those used for application and system files, are also provided by the secondary storage resources.

Beyond sizing considerations, Epic has the following additional storage layout rules and key considerations: 

* Since 2020, all operational database (ODB) workloads must be on all-flash arrays.

* Epic recommends each pool of storage to be on separate physical hardware, including pool1, pool2, pool3, NAS1, and NAS2. 

[NOTE]
A node in a cluster can be considered as a pool of storage. With ONTAP 9.4 or later and AQoS, you can create protected pools using policies.

* New Epic 3-2-1 backup recommendation. 

1. Copy located in remote site (disaster recovery)

2. One of the copies must be on a different storage platform than the primary copy

3. Copies of the data

[NOTE]
Customers who use NetApp SnapMirror to back up NetApp do not meet the 3-2-1 recommendations. The reason is ONTAP to ONTAP does not satisfy the second requirement listed above. You can use SnapMirror directly from ONTAP to object storage on-premises (through StorageGRID, for example) or to the cloud to meet Epic requirements.

For more information about storage mandates, see the following Epic guides available in Galaxy:

* SAN Considerations

* Storage Products and Technology Status (SPaTS)

* Hardware Configuration Guide