---
sidebar: sidebar
permalink: epic/epic-config-files.html
keywords: epic,cache,iris
summary: Epic and file protocols
---

= Epic and file protocols

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Combining NAS and SAN on the same all-flash array is supported. 

[TIP]
====
NetApp recommends using FlexGroup volumes for NAS shares, such as WebBLOB (when available).
====

WebBLOB is up to 95% cold data. You can optionally free space on your all-flash array and tier backups and cold data to object storage on-premises or in the cloud using the link:https://docs.netapp.com/us-en/ontap/fabricpool/index.html[FabricPool^] feature of ONTAP. All of which can be accomplished without any noticeable performance effect. FabricPool is an included feature of ONTAP, Customers can generate a cold (or inactive) data report to review how much benefit could be realized by enabling FabricPool. You can set the age of the data to tier through policy. Epic customers have realized significant savings with this feature.