---
sidebar: sidebar
permalink: epic/epic-ontap-security.html
keywords: epic,cache,iris
summary: Epic on ONTAP security
---

= Epic on ONTAP security

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Security is the number one concern for organizations and healthcare executives today. It has never been more difficult to manage, and organizations are challenged with compliance, data governance, antivirus protection, and ransomware.

A complete guide to Epic and storage security is beyond the scope of this document; however, link:https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf[TR-4569: Security Hardening Guide for ONTAP] details all the extensive and advanced security features available with ONTAP. 

NetApp Active IQ Unified Manager monitors for security violations based on the information included in TR-4569 and reports them in the dashboard to simplify security management. These tools can help your organization meet your security goals to protect, detect, and remediate against attacks.

NetApp has also partnered with security vendors to provide integration through NetApp FPolicy software to enhance your security offering. Furthermore, multifactor (MFA) authentication can be added to secure your Epic environment against unauthorized access with leaked credentials. 

Finally, ONTAP native Snapshot and immutable SnapLock backup technologies offer a unique air gap capability to protect your patient records against ransomware. See a NetApp documentation on link:https://www.netapp.com/pdf.html?item=/media/7334-tr4572.pdf[TR-4572: The NetApp Solution for Ransomware]. For a more strategic approach to security, see link:https://www.netapp.com/pdf.html?item=/media/19756-tr-4829.pdf[TR-4829: NetApp and Zero Trust].
