---
sidebar: sidebar
permalink: epic/epic-arch-storage.html
keywords: epic,cache,iris
summary: Epic storage requirements
---

= Epic storage requirements

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media

[.lead]
Beyond sizing considerations, Epic has the following additional storage layout rules and key considerations: 

* By year 2020, all operational database (ODB) workloads must be on all-flash arrays.

* Epic recommends each pool of storage to be on separate physical hardware, including pool1, pool2, pool3, NAS1, and NAS2. 

Note: A node in a cluster can be considered as a pool of storage. With ONTAP 9.4 or later and AQoS, you can create protected pools using policies.

* New Epic 3-2-1 backup recommendation. The “2” requirement was added with the 2020.

1. Copy located in remote site (disaster recovery)

2. One of the copies must be on a different storage platform than ONTAP

3. Copies of the data

Note: Customers who use NetApp SnapMirror or SnapVault to back up NetApp do not meet the 3-2-1 recommendations. ONTAP to ONTAP does not satisfy the “2” requirement above. You can use SnapMirror directly from ONTAP to object storage on-premises (through StorageGrid, for example) or to the cloud to meet Epic requirements.

For more information about storage mandates, see the following Epic guides available in Galaxy:

* SAN Considerations

* Storage Products and Technology Status (SPaTS)

* Hardware Configuration Guide
