---
sidebar: sidebar
permalink: epic/epic-ontap-overview.html
keywords: epic,cache,iris
summary: Epic on ONTAP is awesome
---

= >>> Level One Title

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media

[.lead]
>>> Placeholder for descriptive lead sentence or paragraph

== Epic on ONTAP

This section covers a long list of considerations for an Epic solution. I am sure every storage vendor makes the same claims, making the platform decision even more complex. This section helps clarify each of these areas regarding NetApp. When examined all together, ONTAP is the clear choice for any healthcare data management system.

Epic is easier with ONTAP

This consideration is first because it is the most important when selecting a data management platform.

ONTAP is a single data management platform you can consolidate Epic workloads with while meeting all of your requirements.

This is a bold statement, and it is transformative to your organization. Why? Only on NetApp can you standardize all your healthcare workloads for SAN, NAS, and Object on a single high data management platform. ONTAP is the most widely deployed storage software in the world and comes with almost 30 years of constant innovation. You can meet all Epic challenges with native ONTAP data management tools and application integration. There is no need to purchase a multitude of third-party tools to fill gaps in the solution.

A lot of storage vendors offer traditional, reliable, and fast block storage. They work well but are typically deployed in silos to run a single workload like production, report, clarity, VDI, VMWare, and NAS. Each of these silos have different hardware and different management tools, and they are typically managed by different IT groups. This traditional approach adds to the biggest problem with healthcare today.

NetApp makes data management easier and more efficient. Instead of throwing money at the problem with oversized silos, ONTAP uses innovation and technology to enable a consistent and guaranteed SLA for each workload on a single platform over any protocol. These capabilities and tools extend out to the cloud of your choice as illustrated in Figure 3.

Figure 3) No more expensive and complex silos.
