---
sidebar: sidebar
permalink: epic/epic-ontap-security.html
keywords: epic,cache,iris
summary: Epic on ONTAP security
---

= Epic on ONTAP security

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Security is the number one concern for organizations and healthcare executives today. It has never been more difficult to manage, and organizations are challenged with compliance, data governance, antivirus protection, and ransomware.

A complete guide to Epic and storage security is beyond the scope of this document; however, link:https://docs.netapp.com/us-en/ontap/ontap-security-hardening/security-hardening-overview.html[Security Hardening Guide for ONTAP^] details all the extensive and advanced security features available with ONTAP. 

NetApp Active IQ Unified Manager monitors for security violations based on the information included in link:https://docs.netapp.com/us-en/ontap/ontap-security-hardening/security-hardening-overview.html[TR-4569^] and reports them in the dashboard to simplify security management. These tools can help your organization meet your security goals to protect, detect, and remediate against attacks.

NetApp has also partnered with security vendors to provide integration through link:https://docs.netapp.com/us-en/ontap/ontap-security-hardening/create-fpolicy.html[NetApp FPolicy^] software to enhance your security offering. Furthermore, link:https://docs.netapp.com/us-en/ontap/authentication/mfa-overview.html[multifactor (MFA) authentication^] can be added to secure your Epic environment against unauthorized access with leaked credentials.

Finally, ONTAP native Snapshot copies and immutable SnapLock technologies with link:https://docs.netapp.com/us-en/netapp-solutions/cyber-vault/ontap-cyber-vault-overview.html[ONTAP cyber vault^], offer a unique air gap capability to protect your patient records against ransomware. See NetApp documentation on link:https://docs.netapp.com/us-en/ontap/ransomware-solutions/ransomware-overview.html[The NetApp Solution for Ransomware^]. For a more strategic approach to security, see link:https://docs.netapp.com/us-en/ontap/zero-trust/zero-trust-overview.html[NetApp and Zero Trust^].