---
sidebar: sidebar
permalink: epic/epic-scope.html
keywords: epic,cache,iris
summary: Epic on ONTAP is awesome
---

= >>> Level One Title

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media

[.lead]
>>> Placeholder for descriptive lead sentence or paragraph

= Purpose

This document describes best practices for integrating NetApp storage into an Epic software environment. It contains the following sections:
* Epic overview” offers NetApp field engineers a technical understanding of the Epic software environment and its storage requirements across various configurations.
* Epic storage considerations" describes important decision-making storage factors when architecting an Epic solution, NetApp reference architecture, and sizing.
* NetApp AFF overview” describes important features of the NetApp AFF solution.
* NetApp storage recommendations” describes NetApp storage configuration best practices for satisfying Epic storage requirements.
* Integration tuning” describes the host-side tuning required by Epic to enable the software to best integrate with NetApp storage.

= Scope

The NetApp storage best practices provided in this document apply to environments with the following characteristics:

* Environments that use the NetApp ONTAP® software version 9.4 and later. NetApp Service Level Manager (SLM) and Adaptive Quality of Service (AQoS) should be used.

* Disaster recovery capabilities.

This document does not cover the following subjects:

* Quantitative performance requirements and sizing guidance, which are addressed in TR-3930i: NetApp Sizing Guidelines for Epic (NetApp login required).

Audience

This document is intended for NetApp, partner solutions engineers (SEs), and professional services personnel. NetApp assumes that the reader has the following background knowledge:

* A solid understanding of SAN and NAS concepts
* Technical familiarity with NetApp ONTAP storage systems
* Technical familiarity with the configuration and administration of ONTAP software
