---
sidebar: sidebar
permalink: microsoft/win_deploy_hyperv.html
keywords: Windows,Hyper-V,VHDX,VM,Virtual
summary: This appendix describes deploying a high availability Hyper-V cluster on NetApp storage.
---
= Deploy Hyper-V cluster
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
This appendix describes deploying a Hyper-V cluster.

== Prerequisites
* At least two Hyper-V servers exist connected to each other.
* At least one virtual switch is configured on each Hyper-V server.
* The failover cluster feature is enabled on each Hyper-V server.
* SMB shares or CSVs are used as shared storage to store VMs and their disks for Hyper-V clustering.
* Storage should not be shared between different clusters. You should have only one CSV/CIFS share per cluster.
* If the SMB share is used as shared storage, then permissions on the SMB share must be configured to grant access to the computer accounts of all the Hyper-V servers in the cluster.

== Deployment
[arabic]
. Log in to one of the Windows Hyper-V servers as a member of the administrator group.
. Start Server Manager**.**
. In the Tools section, click Failover Cluster Manager.
. Click the Create Cluster from Actions menu.
. Provide details for the Hyper-V server that is part of this cluster.
. Validate the cluster configuration. Select Yes when prompted for cluster configuration validation and select the tests required to validate whether the Hyper-V servers pass the prerequisites to be part of the cluster.
. After validation succeeds, the Create Cluster wizard is started. In the wizard, provide the cluster name and the cluster IP address for the new cluster. A new failover cluster is then created for the Hyper-V server.
. Click the newly created cluster in Failover Cluster Manager and manage it.
. Define shared storage for the cluster to use. It can be either an SMB share or a CSV.
. Using an SMB share as shared storage requires no special steps.
* Configure a CIFS share on a NetApp storage controller. To do so, see the section "link:win_smb.html[Provisioning in SMB Environments]".
. To use a CSV as shared storage, complete the following steps:
.. Configure LUNs on a NetApp storage controller. To do so, see the section "Provisioning in SAN Environments."
.. Make sure that all the Hyper-V servers in the failover cluster can see the NetApp LUNs. To do this for all the Hyper-V servers that are part of the failover cluster, make sure that their initiators are added to the initiator group on NetApp storage. Also be sure that their LUNs are discovered and make sure that MPIO is enabled.
.. On any one of the Hyper-V servers in the cluster, complete the following steps:
... Take the LUN online, initialize the disk, create a new simple volume, and format it using NTFS or ReFS.
... In Failover Cluster Manager, expand the cluster, expand Storage, right-click Disks, and then click Add Disks. Doing so opens the Add Disks to a Cluster wizard showing the LUN as a disk. Click OK to add the LUN as a disk.
... Now the LUN is named 'Clustered Disk' and is shown as Available Storage under Disks.
.. Right-click the LUN ('Clustered Disk') and click Add to Cluster Shared Volumes. Now the LUN is shown as a CSV.
.. The CSV is simultaneously visible and accessible from all the Hyper-V servers of the failover cluster at its local location C:\ClusterStorage\.
. Create a highly available VM:
.. In Failover Cluster Manager, select and expand the cluster created previously.
.. Click Roles and then click Virtual Machines in Actions. Click New Virtual Machine.
.. Select the node from the cluster where the VM should reside.
.. In the Virtual Machine Creation wizard, provide the shared storage (SMB share or CSV) as the path to store the VM and its disks.
.. Use Hyper-V Manager to set the shared storage (SMB share or CSV) as the default path to store the VM and its disks for a Hyper-V server.
. Test planned failover. Move VMs to another node using live migration, quick migration, or storage migration (move). Review link:win_deploy_hyperv_lmce.html[Live Migration in a Clustered Environment] for more details.
. Test unplanned failover. Stop cluster service on the server owning the VM.