---
sidebar: sidebar
permalink: microsoft/win_deploy_hyperv_replica_ce.html
keywords: Windows,Hyper-V,VHDX,VM,Virtual
summary: Learn how to deploy and configure Hyper-V replica with Windows Server Failover Cluster.
---
= Deploy Hyper-V replica in a clustered environment
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Learn how to deploy and configure Hyper-V replica with Windows Server Failover Cluster.

== Prerequisites
* You need to have Hyper-V clusters located in the same or in separate geographical locations serving as primary and replica clusters. Review link:win_deploy_hyperv.html[Deploy Hyper-V Cluster] for more details.
* If separate sites are used, then the firewall at each site must be configured to allow communication between the primary and replica clusters.
* The replica cluster must have enough space to store the replicated workloads.

== Deployment
. Enable firewall rules on all the nodes of a cluster. Run the following PowerShell cmdlet with admin privileges on all the nodes in both the primary and replica clusters.

 # For Kerberos authentication
 get-clusternode | ForEach-Object \{Invoke-command -computername $_.name -scriptblock \{Enable-Netfirewallrule -displayname "Hyper-V Replica HTTP Listener (TCP-In)"}}
 
 # For Certificate authentication
 get-clusternode | ForEach-Object \{Invoke-command -computername $_.name -scriptblock \{Enable-Netfirewallrule -displayname "Hyper-V Replica HTTPS Listener (TCP-In)"}}

. Configure the replica cluster.
.. Configure the Hyper-V Replica broker with a NetBIOS name and IP address to use as the connection point to the cluster that is used as the replica cluster.
... Open Failover Cluster Manager.
... Expand the cluster, click Roles, and click the Configure Role from Actions pane.
... Select Hyper-V Replica Broker in the Select Role page.
... Provide the NetBIOS name and IP address to be used as the connection point to the cluster (client access point).
... This process creates a Hyper-V Replica broker role. Verify that it comes online successfully.
.. Configure replication settings.
... Right-click the replica broker created in the previous steps and click Replication Settings.
... Select Enable This Cluster as a Replica Server.
... In the Authentication and Ports section, select the authentication method and port.
... In the authorization and storage section, select the servers allowed to replicate VMs to this cluster. Also, specify the default location where the replicated VMs are stored.

== Replication
Replication is similar to the process described in the section link:win_deploy_hyperv_replica_oce[Replica Outside a Clustered Environment].